baseURL = "https://sehareng-droid.github.io/AI-blog/"
languageCode = "en-us"
title = "Agentic AI Blog 2026"
theme = "ananke"

relativeURLs = true
canonifyURLs = true

[pagination]
  pagerSize = 5

enableRobotsTXT = true

[params]
  author = "Sehar Naveed"
  description = "AI, Automation, and Agents Blog"
  showDate = true
